site_name: Courseplay
site_url: https://sitename.example

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        - locale: en
          name: English
        - locale: pt_BR
          name: Brasil
        - locale: cs
          name: Čeština
        - locale: ca
          name: Català
        - locale: cs
          name: Česko
        - locale: da
          name: Dansk
        - locale: de
          name: Deutsch
        - locale: es
          name: Español (EA)
        - locale: es
          name: Español
        - locale: fr_CA
          name: Français (Canada)
        - locale: fi
          name: Suomi
        - locale: fr
          name: Français
        - locale: hu
          name: Magyar
        - locale: it
          name: Italiano
        - locale: ja
          name: 日本語
        - locale: ko
          name: 한국어
        - locale: nl
          name: Nederlands
        - locale: no
          name: Norsk
        - locale: pl
          name: Polski
        - locale: pt
          name: Português
        - locale: ro
          name: Română
        - locale: ru
          name: Русский
        - locale: sv
          name: Svenska
        - locale: tr
          name: Türkçe
        - locale: uk
          name: Українська

extra:
  social:
    - icon: simple/github
      link: https://github.com/Courseplay/Courseplay_FS25/releases

copyright: Copyright &copy; 2025 Courseplay Dev Team
